// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsSXJXKhcn0Wiej18VHPsfrMRakzMMY0w',
    appId: '1:79105574650:web:496a95dc589c37bc64eb43',
    messagingSenderId: '79105574650',
    projectId: 'flutter-projects-a86d2',
    authDomain: 'flutter-projects-a86d2.firebaseapp.com',
    storageBucket: 'flutter-projects-a86d2.appspot.com',
    measurementId: 'G-TS2N426B22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw6UnIfInNqj4wFEoi6lM3G8nne4ib11o',
    appId: '1:79105574650:android:dd99543e6b3beee064eb43',
    messagingSenderId: '79105574650',
    projectId: 'flutter-projects-a86d2',
    storageBucket: 'flutter-projects-a86d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPWNdIsbe5uWYY4DhfmwR9MM2VJcmKnVw',
    appId: '1:79105574650:ios:05af8e8aca763f4464eb43',
    messagingSenderId: '79105574650',
    projectId: 'flutter-projects-a86d2',
    storageBucket: 'flutter-projects-a86d2.appspot.com',
    iosBundleId: 'com.example.pushNotificationsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPWNdIsbe5uWYY4DhfmwR9MM2VJcmKnVw',
    appId: '1:79105574650:ios:7a07bc3b62f4a7fb64eb43',
    messagingSenderId: '79105574650',
    projectId: 'flutter-projects-a86d2',
    storageBucket: 'flutter-projects-a86d2.appspot.com',
    iosBundleId: 'com.example.pushNotificationsApp.RunnerTests',
  );
}
